# Generated by Django 3.2 on 2023-05-24 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230518_1853'),
        ('reviews', '0005_alter_title_genre'),
    ]

    operations = [
    ]
